local username = 'r.rj.wang@gmail.com'
local password = 'VfJcVYMrFKlqy9Kbn0yLqA'
local server = 'smtp.mandrillapp.com'

storage.ufa_count = (storage.ufa_count or 0) + 1
ufa_count = tonumber(storage.ufa_count)

players = {{1,"Kevin Durant, OKC SF",32,"",""},
{11,"Dwyane Wade, Mia SG",20,"",""},
{21,"Ersan Ilyasova, Mil SF",16,"UFA","Cho"},
{61,"Gerald Henderson, Cha SG",6,"UFA","Tom"},
{62,"Andrei Kirilenko, Bkn SF",6,"",""},
{63,"Kevin Martin, Min SG",4,"UFA","Larry/Kevin"},
{64,"Jarrett Jack, Cle PG",4,"",""},
{65,"Danilo Gallinari, Den SF",4,"",""},
{2,"LeBron James, Mia SF",32,"",""},
{12,"Josh Smith, Det PF",20,"",""},
{22,"Rudy Gay, Tor SF",16,"UFA","Roger"},
{66,"Gordon Hayward, Uta SG",4,"UFA","Cho"},
{67,"DeMar DeRozan, Tor SG",4,"UFA","Peter/Mike"},
{68,"Nene, Wsh C",4,"",""},
{69,"Marcin Gortat, Pho C",4,"UFA","Larry/Kevin"},
{70,"Manu Ginobili, SA SG",4,"",""},
{3,"James Harden, Hou SG",32,"UFA","Cho"},
{13,"Ty Lawson, Den PG",20,"UFA","Tom"},
{23,"Blake Griffin, LAC PF ",16,"",""},
{71,"Shawn Marion, Dal SF",4,"",""},
{72,"MarShon Brooks, Bos SG",2,"",""},
{73,"Arron Afflalo, Orl SG ",2,"UFA","Vince"},
{74,"Mario Chalmers, Mia PG",2,"UFA","Peter/Mike"},
{75,"Andre Miller, Den PG",2,"",""},
{4,"Chris Paul, LAC PG",32,"",""},
{14,"LaMarcus Aldridge, Por PF",20,"UFA","Roger"},
{24,"Paul Pierce, Bkn SF",16,"",""},
{76,"Jordan Crawford, Bos SG",2,"",""},
{77,"Kris Humphries, Bos PF",2,"UFA","Eric"},
{78,"Dorell Wright, Por SF",2,"UFA","Peter/Mike"},
{79,"Trevor Ariza, Wsh SF ",2,"",""},
{80,"Glen Davis, Orl PF",2,"",""},
{5,"Russell Westbrook, OKC PG",32,"UFA","Cho"},
{15,"Al Horford, Atl C",20,"",""},
{25,"Mike Conley, Mem PG",16,"UFA","Roger"},
{81,"Andrea Bargnani, NY PF",2,"",""},
{82,"Mo Williams, Por PG",2,"",""},
{83,"Brandan Wright, Dal PF",2,"",""},
{84,"Brandon Bass, Bos PF",2,"UFA","Mike"},
{85,"J.J. Redick, LAC SG",1,"UFA","Tom"},
{6,"Kevin Love, Min PF",26,"UFA","Mike"},
{16,"Al Jefferson, Cha C",20,"",""},
{26,"Dwight Howard, Hou C ",16,"",""},
{86,"Darren Collison, LAC PG",1,"",""},
{87,"Luis Scola, Ind PF",1,"",""},
{88,"Tony Allen, Mem SG",1,"UFA","Roger"},
{89,"Wesley Johnson, LAL SF",1,"",""},
{90,"Chase Budinger, Min SF",1,"",""},
{7,"Nicolas Batum, Por SF",26,"UFA","Will"},
{17,"Rajon Rondo, Bos PG",20,"",""},
{27,"Monta Ellis, Dal PG",16,"",""},
{91,"Jason Terry, Bkn SG",1,"UFA","Mike"},
{92,"Luke Ridnour, Mil PG",1,"UFA","Will"},
{93,"Devin Harris, Dal PG",1,"",""},
{94,"Reggie Evans, Bkn PF ",1,"",""},
{95,"Mike Miller, Mem SF",1,"",""},
{8,"Serge Ibaka, OKC C",26,"UFA","Steve"},
{18,"Brandon Jennings, Det PG",20,"",""},
{28,"DeMarcus Cousins, Sac PF",16,"",""},
{96,"Rodney Stuckey, Det SG",1,"UFA","Eric"},
{97,"Carl Landry, Sac PF",1,"",""},
{98,"Marcus Thornton, Sac SG",1,"UFA","Lam"},
{99,"Ray Allen, Mia SG",1,"",""},
{100,"DeAndre Jordan, LAC C",1,"UFA","Peter/Mike"},
{9,"Deron Williams, Bkn PG",26,"",""},
{19,"Jrue Holiday, Nor PG",20,"UFA","Tom"},
{29,"Chris Bosh, Mia PF",16,"",""},
{101,"Alonzo Gee, Cle SF",1,"",""},
{102,"Taj Gibson, Chi PF",1,"UFA","Andrew"},
{103,"Jared Dudley, LAC SF",1,"UFA","Will"},
{104,"Avery Bradley, Bos SG",1,"",""},
{105,"Kyle Korver, Atl SG",1,"",""},
{10,"Dirk Nowitzki, Dal PF",20,"",""},
{20,"Tony Parker, SA PG",16,"UFA","Steve"},
{30,"Ryan Anderson, Nor PF",12,"UFA","Cho"},
{106,"Kosta Koufos, Mem PF",1,"",""},
{107,"Josh McRoberts, Cha PF",1,"",""},
{108,"Ramon Sessions, Cha PG ",1,"",""},
{109,"Jason Thompson, Sac PF",1,"",""},
{110,"Markieff Morris, Pho PF",1,"",""},
{31,"Thaddeus Young, Phi SF",12,"UFA","Tom"},
{32,"David West, Ind PF",12,"",""},
{33,"Tyreke Evans, Nor PG",12,"",""},
{34,"Jeff Teague, Atl PG",12,"UFA","Will"},
{35,"George Hill, Ind PG",12,"",""},
{36,"Luol Deng, Chi SF",12,"UFA","Roger"},
{111,"Patrick Beverley, Hou PG",1,"",""},
{112,"Beno Udrih, NY PG",1,"",""},
{37,"Andre Iguodala, GS SF",12,"",""},
{38,"Pau Gasol, LAL PF",12,"",""},
{39,"Paul Millsap, Atl PF",12,"UFA","Will"},
{40,"Wesley Matthews, Por SG",8,"UFA","Roger"},
{41,"Danny Granger, Ind SF",8,"",""},
{42,"Steve Nash, LAL PG",8,"",""},
{113,"DeJuan Blair, Dal PF",1,"UFA","Eric"},
{114,"Nick Young, LAL SG",1,"UFA","Eric"},
{43,"Jeremy Lin, Hou PG ",8,"",""},
{44,"Kobe Bryant, LAL SG",8,"",""},
{45,"Nikola Pekovic, Min C",8,"UFA","Andrew"},
{46,"Omer Asik, Hou C",8,"UFA","Tom"},
{47,"Jameer Nelson, Orl PG",8,"UFA","Cho"},
{48,"Kevin Garnett, Bkn PF",8,"",""},
{115,"Daniel Gibson, Cle PG",1,"UFA","Peter/Mike"},
{116,"Hedo Turkoglu, Orl SF",1,"UFA","Roger"},
{49,"Amar'e Stoudemire, NY PF",8,"",""},
{50,"Kyle Lowry, Tor PG",8,"UFA","Steve"},
{51,"J.J. Hickson, Den PF",8,"UFA","Roger"},
{52,"Andrew Bogut, GS C",6,"",""},
{53,"Gerald Wallace, Bos SF",6,"",""},
{54,"Evan Turner, Phi SG",6,"",""},
{117,"Marvin Williams",1,"UFA","Steve"},
{118,"D.J. Augustin, Tor PG",1,"UFA","Vince"},
{55,"Joe Johnson, Bkn SG",6,"",""},
{56,"Anderson Varejao, Cle C",6,"",""},
{57,"Tyson Chandler, NY C",6,"UFA","Cho"},
{58,"Andrew Bynum, Cle C",6,"UFA","Tom"},
{59,"Eric Gordon, Nor SG ",6,"UFA","Peter/Mike"},
{60,"JaVale McGee, Den C",6,"UFA","Roger"},
{119,"Michael Beasley Mia PF",1,"UFA","Vince"},
{120,"Ed Davis, Mem PF",1,"",""},
{121,"Xavier Henry, LAL SG",1,"",""},
{122,"Timofey Mozgov, Den C",1,"",""},
{123,"Tiago Splitter, SAS C",1,"",""}}


if ufa_count <= table.getn(players) then
  if players[ufa_count][4] == "" then
    email_text = "2013 Veteran Auction #" .. players[ufa_count][1] .. ": " .. players[ufa_count][2] .. ", minimum bid $" .. players[ufa_count][3]
  else
    email_text = "2013 Veteran Auction #" .. players[ufa_count][1] .. ": " .. players[ufa_count][2] .. ", minimum bid $" .. players[ufa_count][3] .. " (UFA: " .. players[ufa_count][5] .. ")"
  end

  email.send {
    server = server,
    username = username,
    password = password,
    from = 'FBKL Auction Bot <r.rj.wang@gmail.com>',
    to = 'franchise-basketball-keeper-league@googlegroups.com',
    subject = email_text,
    text = email_text
  }   
  return "Email sent. Thanks!"
end

return "No more auctions"
