local username = 'r.rj.wang@gmail.com'
local password = 'VfJcVYMrFKlqy9Kbn0yLqA'
local server = 'smtp.mandrillapp.com'

storage.ufa_count_2014 = (storage.ufa_count_2014 or 0) + 1
ufa_count = tonumber(storage.ufa_count_2014)

players = {{1,"Kevin Durant, OKC SF",32,"",""},
  {9,"Dirk Nowitzki, Dal PF",26,"",""},
  {17,"Mike Conley, Mem PG",16,"",""},
  {25,"Wesley Matthews, Por SG",12,"",""},
  {71,"Larry Sanders, Mil C",1,"",""},
  {72,"Mike Dunleavy, Chi SG",1,"",""},
  {73,"Evan Turner, Bos SG",1,"",""},
  {74,"Matt Barnes, LAC SF",1,"",""},
  {2,"LeBron James, Cle SF",32,"",""},
  {10,"Al Jefferson, Cha C",20,"",""},
  {18,"Pau Gasol, Chi PF",16,"",""},
  {26,"Chandler Parsons, Dal SF",12,"UFA","Mike"},
  {75,"Kyle O'Quinn, Orl PF",1,"",""},
  {76,"Jarrett Jack, Bkn PG",1,"",""},
  {77,"Andrea Bargnani, NY PF",1,"",""},
  {78,"Henry Sims, Phi C",1,"",""},
  {3,"Kevin Love, Cle PF",32,"",""},
  {11,"Goran Dragic, Pho PG",20,"UFA","Larry/Kevin"},
  {19,"Al Horford, Atl C",16,"",""},
  {27,"Kevin Martin, Min SG",12,"",""},
  {79,"Samuel Dalembert, NY C",1,"",""},
  {80,"Tony Allen, Mem SG",1,"",""},
  {81,"Caron Butler, Det SF",1,"",""},
  {82,"James Johnson, Tor SF",1,"",""},
  {4,"Chris Paul, LAC PG",32,"",""},
  {12,"Rajon Rondo, Bos PG",20,"",""},
  {20,"David Lee, GS PF",16,"",""},
  {28,"Jrue Holiday, Nor PG",12,"",""},
  {83,"Brandan Wright, Dal PF",1,"",""},
  {84,"Steve Nash, LAL PG",1,"",""},
  {85,"James Anderson, FA SG",1,"",""},
  {86,"JaVale McGee, Den C",1,"",""},
  {5,"James Harden, Hou SG",26,"",""},
  {13,"Ty Lawson, Den PG",20,"",""},
  {21,"Brook Lopez, Bkn C",16,"",""},
  {29,"Derrick Rose, Chi PG",12,"",""},
  {87,"O.J. Mayo, Mil SG",1,"UFA","Lam"},
  {88,"Andray Blatche, Bkn PF",1,"",""},
  {89,"Drew Gooden, Wsh PF",1,"",""},
  {90,"Ray Allen, FA SG",1,"",""},
  {6,"Russell Westbrook, OKC PG",26,"",""},
  {14,"Marc Gasol, Mem C",20,"UFA","Tom"},
  {22,"Dwyane Wade, Mia SG",16,"",""},
  {30,"Josh Smith, Det SF",12,"",""},
  {91,"Greivis Vasquez, Tor PG",1,"UFA","Lam"},
  {92,"Jordan Farmar, LAC PG",1,"",""},
  {93,"Kevin Garnett, Bkn PF",1,"",""},
  {94,"Gerald Wallace, Bos SF",1,"",""},
  {7,"Carmelo Anthony, NY SF",26,"",""},
  {15,"Kobe Bryant, LAL SG",20,"",""},
  {23,"Thaddeus Young, Min SF",16,"",""},
  {31,"Gordon Hayward, Uta SG",12,"",""},
  {95,"Steve Blake, Por PG",1,"",""},
  {96,"Kent Bazemore, Atl SG",1,"",""},
  {97,"Andrew Bynum, FA C",1,"",""},
  {98,"Kris Humphries, Wsh PF",1,"",""},
  {8,"Serge Ibaka, OKC PF",26,"",""},
  {16,"Monta Ellis, Dal SG, PG",20,"",""},
  {24,"Deron Williams, Bkn PG",12,"",""},
  {32,"Ryan Anderson, Nor PF",12,"",""},
  {99,"Martell Webster, Wsh SF",1,"",""},
  {100,"Patrick Patterson, Tor PF",1,"",""},
  {101,"Aaron Brooks, Chi PG",1,"",""},
  {102,"Nate Robinson, Den PG",1,"",""},
  {33,"Tim Duncan, SA PF",12,"",""},
  {34,"Marcin Gortat, Wsh C",12,"",""},
  {35,"Luol Deng, Mia SF",12,"",""},
  {36,"Jeff Green, Bos SF",8,"",""},
  {37,"Tyreke Evans, Nor SF",8,"",""},
  {38,"Zach Randolph, Mem PF",8,"",""},
  {39,"Brandon Jennings, Det PG",8,"",""},
  {40,"Wilson Chandler, Den SF",8,"UFA","Peter/Mike"},
  {41,"Spencer Hawes, LAC C",8,"UFA","Peter/Mike"},
  {42,"David West, Ind PF",8,"",""},
  {43,"Paul Pierce, Wsh SF",8,"",""},
  {44,"Robin Lopez, Por C",8,"UFA","Vince","",""},
  {45,"Randy Foye, Den SG",8,"UFA","Roger","",""},
  {46,"Jameer Nelson, Dal PG",8,"",""},
  {47,"J.J. Redick, LAC SG",6,"",""},
  {48,"Joe Johnson, Bkn SG",6,"",""},
  {49,"Danilo Gallinari, Den SF",6,"",""},
  {50,"Anderson Varejao, Cle C",4,"",""},
  {51,"Jared Sullinger, Bos PF",4,"",""},
  {52,"Shawn Marion, Cle SF",4,"",""},
  {53,"Andre Iguodala, GS SF",4,"",""},
  {54,"Khris Middleton, Mil SF",4,"",""},
  {55,"Amar'e Stoudemire, NY PF",4,"",""},
  {56,"D.J. Augustin, Det PG",4,"",""},
  {57,"Mario Chalmers, Mia PG",4,"",""},
  {58,"Manu Ginobili, SA SG",4,"",""},
  {59,"Roy Hibbert, Ind C",4,"UFA","Roger"},
  {60,"Louis Williams, Tor PG",4,"UFA","Eric"},
  {61,"George Hill, Ind PG",2,"",""},
  {62,"Ramon Sessions, Mil PG",2,"",""},
  {63,"Ersan Ilyasova, Mil PF",2,"",""},
  {64,"Patty Mills, SA PG",2,"",""},
  {65,"Corey Brewer, Min SF",2,"UFA","Peter/Mike"},
  {66,"Shaun Livingston, GS PG",2,"",""},
  {67,"Gerald Henderson, Cha SG",2,"",""},
  {68,"Vince Carter, Mem SG",2,"",""},
  {69,"Carlos Boozer, LAL PF",2,"",""},
  {70,"Raymond Felton, Dal PG",1,"",""},
  {103,"Alec Burks, Uta SG",1,"",""},
  {104,"Iman Shumpert, NY SG",1,"",""},
  {105,"Enes Kanter, Uta C",1,"",""},
  {106,"Norris Cole, Mia PG",1,"",""}}

if ufa_count <= table.getn(players) then
  if players[ufa_count][4] == "" then
    email_text = "2014 Veteran Auction #" .. players[ufa_count][1] .. ": " .. players[ufa_count][2] .. ", starting bid $" .. players[ufa_count][3]
  else
    email_text = "2014 Veteran Auction #" .. players[ufa_count][1] .. ": " .. players[ufa_count][2] .. ", starting bid $" .. players[ufa_count][3] .. " (UFA: " .. players[ufa_count][5] .. ")"
  end

  email.send {
    server = server,
    username = username,
    password = password,
    from = 'FBKL Auction Bot <r.rj.wang@gmail.com>',
    to = 'franchise-basketball-keeper-league@googlegroups.com',
    -- to = 'r.rj.wang@gmail.com',
    subject = email_text,
    text = email_text
  }
  return "Email sent. Thanks!"
end

return "No more auctions"
